Languages
Metaburn/cobudget-new pull request #18
Opened 2024-04-18 15:13 UTC by levitomer

2024-04-18 15:28 UTC, Ronbalt requested changes

2024-04-18 15:28 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "+n0CL7": "אַחֲרָיוּת",
חושש שסימני פיסוק לא יתקבלו טוב בכל הדפדפנים, מציע להוריד

2024-04-18 15:28 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "0KKXrH": "תַקצִיב",
Same

2024-04-18 15:28 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "0vJAZN": "תודה! ",
The translation here reduced the context, the original was something about comments.

2024-04-18 15:28 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "1gZbl7": "{bucketName} חדש פורסם",
גם זה פחות טוב, אצלנו יש קונטקסט של חלום, ופה זה ירד.
יש לנו חלק מהמקומות שבכוונה הוספנו חלומות כדי לחבר למונחים שלנו.

2024-04-18 15:30 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "0vJAZN": "תודה! ",
Prior translation was:

תודה לך! התגובה שלך נשמרה

2024-04-18 15:30 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "0vJAZN": "תודה! ",
Specifically talking about "0vJAZN"

2024-04-18 15:31 UTC, Ronbalt commented on ui/lang/he-IL.json
> +  "1gZbl7": "{bucketName} חדש פורסם",
במקור 1gZbl7 היה מתורגם כך:

חלום חדש בשם {bucketName} נוצר

2024-04-19 13:55 UTC, rootux approved these changes

2024-04-19 13:55 UTC, merged